Repository yourssu/Soomsil-Web, pull requests merged in 2024-09, with the labels that each got.

#294 fix: 서랍장 서비스 등록 시, 리다이렉트 URL myproduct로 이동
  src/drawer/pages/Register/Register.tsx
Labels: fix, drawer

#286 remove: `MyMenuList`의 오픈소스 사용정보 메뉴 삭제
  src/home/components/MyMenuList/MyMenuList.tsx
  third-party-licenses.txt
Labels: bug, fix, home

#296 fix: version 1.0.0 으로 푸터 텍스트 수정
  src/drawer/components/Footer/Footer.tsx
Labels: bug, fix

#295 fix: 랭킹 카테고리 결과 없는 경우 아무것도 안뜨는 상태
  src/drawer/components/EmptyScreen/EmptyScreen.tsx
  src/drawer/constants/empty.constant.ts
  src/drawer/pages/NewRelease/NewRelease.tsx
  src/drawer/pages/Provider/Provider.tsx
  src/drawer/pages/StarRanking/StarRanking.tsx
  src/drawer/types/emptyState.type.ts
Labels: bug, fix, drawer

#301 fix: 회원가입 시 닉네임 검증을 하지 않는 문제
  package.json
  pnpm-lock.yaml
Labels: fix, home

#298 fix: formatDateTime에서 시간이 제대로 변환되지 않는 문제
  src/utils/formatDateTime.ts
Labels: bug, fix

#299 refactor : useMutation으로 api 호출 방식 통일
  src/home/apis/authVerification.ts
  src/home/apis/getAuthVerificationCheck.ts
  src/home/apis/postAuthSignUp.ts
  src/home/apis/postAuthVerificationEmail.ts
  src/home/components/ResetPasswordContents/EmailInput/EmailInput.tsx
  src/home/components/ResetPasswordContents/EmailInput/useEmailInputForm.ts
  src/home/components/ResetPasswordContents/EmailVerification/useEmailVerification.ts
  src/home/components/SignupContents/EmailAuth/useEmailAuth.ts
  src/home/components/SignupContents/EmailForm/EmailForm.tsx
  src/home/components/SignupContents/EmailForm/useEmailForm.ts
  src/home/components/SignupContents/SignupForm/useSignupFormConfirm.tsx
  src/home/hooks/useGetAuthVerificationCheck.ts
  src/home/hooks/usePostAuthSignUp.ts
  src/home/hooks/usePostAuthVerificationEmail.ts
  src/home/types/Auth.type.ts
Labels: refactor
